### ISSUE TITLE
No Unicode support 

### ISSUE THREAD

**Issue by imehdihosseini** [xergio/xrg.es#2]
There is no Unicode support, for example when you want to test a regex like this `^[\x{0600}-\x{06EF}]+$` (persian alphabet) the Result will be something like this:

Compilation failed: character value in \x{...} sequence is too large at offset 7

**Comment by xergio** [comment]
Use the modifier "u" to allow UTF-8 strings. More info: http://php.net/manual/en/reference.pcre.pattern.modifiers.php 

Example: https://xrg.es/#8vte6h

**Comment by coffeetalkh** [comment]
Works well, thanks xergio :+1:
